hello/urls.py
from django.urls import path
from hello import views

urlpatterns = [
    path("", views.index, name='index'),    
    path('pedro', views.pedro, name ='pedro'),
    path('david', views.david, name ='david'),
    path('<str:name>',views.greet, name='greet')
]

my_new_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls'))
]

newyear/urls.py
from django.urls import path
from newyear import views

app_name = 'newyear'
urlpatterns = [
    path('',views.index,name='index')
]

tasks/urls.py
from django import urls
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add')
 ]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request): #http request user made to enter our webpage
    return render(request, 'hello/index.html')

def pedro(request):
    return HttpResponse('Hello Pedro')

def david(request):
    return HttpResponse('Hello David')

def greet(request,name):
    return render(request, 'hello/greet.html', {
        'name': name.capitalize(),
    })

newyear/views.py
from django.shortcuts import render
from datetime import datetime

# Create your views here.
def index(request):
    now = datetime.today()
    return render(request, 'newyear/index.html',{
        'newyear': now.month == 1 and now.day == 1
    })

tasks/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django import forms, http
from django.urls import reverse

# Create your views here.
def index(request):
    if 'tasks' not in request.session:
        request.session['tasks'] = []
    return render(request, 'tasks/index.html',{
        'tasks': request.session['tasks']
    })
    
def add(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            request.session['tasks'] += [task]
            return HttpResponseRedirect(reverse('tasks:index'))
        else:
            return render(request,'tasks/add.html',{
                'form': form
            })
    return render(request, 'tasks/add.html',{
        'form': NewTaskForm()
    })


#Create forms easily
class NewTaskForm(forms.Form):
    task = forms.CharField(label='New Task')
    #priority = forms.IntegerField(label='Priority',min_value=1,max_value=10)

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello, {{ name }}!</h1>
</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello world!</h1>
</body>
</html>

newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
</head>
<body>
    {% if newyear %}
        <h1> YES </h1>
    {% else %}
        <h1> NO </h1>
    {% endif %}
</body>
</html>

tasks/templates/tasks/add.html
{%extends 'tasks/layout.html'%}

{%block body%}
    <h1>Add Task</h1>
    <form action="{%url 'tasks:add'%}" method="post">
        {%csrf_token%}
        <!-- <input type="text" name="task" > -->
        {{form}}
        <input type="submit">
    </form>
    <a href="{%url 'tasks:index'%}">View Tasks</a>
{%endblock%}

tasks/templates/tasks/index.html
{%extends 'tasks/layout.html'%}

{%block body%}
    <h1>Tasks</h1>    
    <ul>
        {%for task in tasks%}
            <li>{{task}}</li>
        {%empty%}
            <li>No Tasks</li>
        {%endfor%}
    </ul>
    <a href="{%url 'tasks:add'%}">Add a new task</a>
{%endblock%}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%block body%}
    
    {%endblock%}
</body>
</html>